### PR TITLE
H5py compatibility

### LINKED ISSUE #349: [h5py] the API has changed ... fabio needs to adapt.

### PR DESCRIPTION
**Pull request by kif**
close #349

### CODE REVIEW

**Comment by vallsv** [comment]
LGTM.

But as you put a `mode=` everywhere, maybe it fine to do the same for eiger images.

**Comment by vallsv** [comment]
Be careful, `minor correction in esperanto header parsing`, you are working on your h5py branch ;-)

**Comment by kif** [comment]
@vallsv : You are right ... I reverted those commits, they will be part of another PR.

**Comment by vallsv** [comment]
That's merged

**Pull request merged**
