### PR TITLE
FileI0.read and FileIO.write have a limit in size for a single operation

### LINKED ISSUE #464: FileIO size limit
`FileIO.read` and `FileIO.write` may read/write less bytes than requested, in which case you need multiple calls.

For example:
```python
import os
from io import FileIO

MAX = 2 ** 31 - 4096

filename = "test.dat"
nbytes = MAX + 1
print("Data size bytes:", nbytes)

data = b"0" * nbytes
for openctx in (open, FileIO):
    with openctx(filename, "wb") as f:
        nwritten = 0
        n = 0
        while nwritten < nbytes:
            nwritten += f.write(data[nwritten:])
            n += 1
    print(f"\nFile size bytes: {os.stat(filename).st_size} (written in {n} times)")

    with openctx(filename, "rb") as f:
        nbytesread = 0
        nmissing = nbytes
        n = 0
        while nmissing:
            nbytesread += len(f.read(nmissing))
            nmissing = nbytes - nbytesread
            n += 1
        print(f"Read size bytes: {nbytesread} (read in {n} times)")
```

In other words, Fabio cannot handle images larger that 2GB.

### PR DESCRIPTION
**Pull request by woutdenolf**
Closes #464

### CODE REVIEW

**Comment by woutdenolf** [comment]
Not sure why `FileIO` is used as a base class instead of `TextIOWrapper` (which is what python's `open` returns).

**Comment by woutdenolf** [comment]
I can add a test but this would need 2GB of memory, which might be too much for CI. I could use `psutil` to check the memory before running the test. I tested manually.

**Comment by kif** [comment]
Hi Wout,
Thanks for the PR. It would be interesting to have such a test, even if it is skipped for CI.

**Comment by woutdenolf** [comment]
In analogy with other tests I skip these memory-heavy tests based on the log level.

**Comment by kif** [comment]
Great !

**Pull request merged**
