### PR TITLE
testcase for v0.10.0 -> v0.10.1 FilenameObjects

### PR DESCRIPTION
**Pull request by jonwright**

### CODE REVIEW

**Comment by jonwright** [comment]
So I see the CI is failing but I am not sure why: it seems to be a problem of finding testdata? On my system it fails on a checkout of v0.10.0 and passes on v0.10.1.

**Comment by vallsv** [comment]
Looks like problem with gzip, bzip. @kif any idea? Is it about the remove of the patch of the gzip lib?

**Comment by vallsv** [comment]
Maybe a missing dependency?

**Comment by jonwright** [comment]
I think I am doing a bad tearDown - I will try again...

**Pull request closed without merging**
