### PR TITLE
408 cbf xds

### LINKED ISSUE #408: bug when parsing CIF headers in CBF files
This bug is 

```TypeError                                 Traceback (most recent call last)
<ipython-input-2-90a35d140318> in <module>
----> 1 fabio.open("FRAME.cbf")

/usr/lib/python3/dist-packages/fabio/openimage.py in openimage(filename, frame)
    165         obj = _openimage(filename)
    166         logger.debug("Attempting to read frame %s from %s with reader %s" % (frame, filename, obj.classname))
--> 167         obj = obj.read(obj.filename, frame)
    168     return obj
    169 

/usr/lib/python3/dist-packages/fabio/cbfimage.py in read(self, fname, frame, check_MD5, only_raw)
    236 
    237         infile = self._open(fname, "rb")
--> 238         self._readheader(infile)
    239 
    240         logger.debug("CBS type %s len %s" % (type(self.cbs), len(self.cbs)))

/usr/lib/python3/dist-packages/fabio/cbfimage.py in _readheader(self, inStream)
    121         :param file inStream: file containing the Cif Binary part.
    122         """
--> 123         self._read_cif_header(inStream)
    124         self._read_binary_section_header(inStream)
    125 

/usr/lib/python3/dist-packages/fabio/cbfimage.py in _read_cif_header(self, inStream)
    153         else:
    154             header_data = b"".join(blocks) + inStream.read()
--> 155         self.cif._parseCIF(header_data)
    156 
    157         # backport contents of the CIF data to the headers

/usr/lib/python3/dist-packages/fabio/cbfimage.py in _parseCIF(self, bytes_text)
    501 
    502             print(fields[i:i+2])
--> 503             if fields[i][0] == self.UNDERSCORE and fields[i + 1][0] != self.UNDERSCORE:
    504                 try:
    505                     data = fields[i + 1].decode("ASCII")

TypeError: 'int' object is not subscriptable

```

### PR DESCRIPTION
**Pull request by kif**
close #408

### CODE REVIEW

**Comment by kif** [comment]
@shibom can you confirm it fixes your issue ?

**Comment by shibom** [comment]
> @shibom can you confirm it fixes your issue ?

can I get this version from conda/pip? or do i need to install from the source code?

**Comment by shibom** [comment]
> > @shibom can you confirm it fixes your issue ?
> 
> can I get this version from conda/pip? or do i need to install from the source code?

@kif I successfully installed the source code from master branch and tried to open FRAME.cbf. It still complains about "int" data type. have you pushed to your master branch? or shall I use the version "label"? 

In [2]: fabio.open('FRAME.cbf')                                                                                                                                         
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-eb5c8d8730da> in <module>
----> 1 fabio.open('FRAME.cbf')

/opt/anaconda3/lib/python3.7/site-packages/fabio/openimage.py in openimage(filename, frame)
    177         obj = _openimage(filename)
    178         logger.debug("Attempting to read frame %s from %s with reader %s" % (frame, filename, obj.classname))
--> 179         obj = obj.read(obj.filename, frame)
    180     return obj
    181 

/opt/anaconda3/lib/python3.7/site-packages/fabio/cbfimage.py in read(self, fname, frame, check_MD5, only_raw)
    236 
    237         infile = self._open(fname, "rb")
--> 238         self._readheader(infile)
    239 
    240         logger.debug("CBS type %s len %s" % (type(self.cbs), len(self.cbs)))

/opt/anaconda3/lib/python3.7/site-packages/fabio/cbfimage.py in _readheader(self, inStream)
    117         :param file inStream: file containing the Cif Binary part.
    118         """
--> 119         self._read_cif_header(inStream)
    120         self._read_binary_section_header(inStream)
    121 

/opt/anaconda3/lib/python3.7/site-packages/fabio/cbfimage.py in _read_cif_header(self, inStream)
    149         else:
    150             header_data = b"".join(blocks) + inStream.read()
--> 151         self.cif._parseCIF(header_data)
    152 
    153         # backport contents of the CIF data to the headers

/opt/anaconda3/lib/python3.7/site-packages/fabio/cbfimage.py in _parseCIF(self, bytes_text)
    506             if len(fields[i + 1]) == 0:
    507                 fields[i + 1] = self.QUESTIONMARK
--> 508             if fields[i][0] == self.UNDERSCORE and fields[i + 1][0] != self.UNDERSCORE:
    509                 try:
    510                     data = fields[i + 1].decode("ASCII")

TypeError: 'int' object is not subscriptable

**Comment by kif** [comment]
This is still a pull-request, the branch is not yet merged. As the tests passed, I can merge it and then you will be able to build from the master branch. Please report here (even if the PR is merged), to confirm it works for you.

**Pull request merged**
