### PR TITLE
fix regex regression in Python 3.7

### PR DESCRIPTION
**Pull request by kif**
A better solution probably exists ... 
But fabio 0.7.0 is not compatible with python 3.7

### CODE REVIEW

**Comment by kif** [comment]
On Sat, 30 Jun 2018 00:26:19 -0700
Serhiy Storchaka <notifications@github.com> wrote:

> You can use `r"\s*[,:=\s]\s*"`.

I am not an expert at all of regex :)... Thanks for the tip, I will try

**Comment by vallsv** [comment]
Yes, it would be better to find why it is not working.
Maybe the grouping is pointless for the split function and then avoided now, but i don't see why.

**Comment by serhiy-storchaka** [comment]
It is not working in Python 3.7 because the behavior of `re.split()` was changed. It supports now splitting on empty strings, and the pattern `r"\s*(?:[,:=]\s*)?"` can match an empty string.
```python
>>> re.compile("\s*(?:[,:=]\s*)?").split("a = b", 1)
<stdin>:1: DeprecationWarning: invalid escape sequence \s
['', 'a = b']
```

Python 3.5 and 3.6 emitted a warning about this.
```python
>>> re.compile("\s*(?:[,:=]\s*)?").split("a = b", 1)
<stdin>:1: DeprecationWarning: invalid escape sequence \s
__main__:1: FutureWarning: split() requires a non-empty pattern match.
['a', 'b']
```

The pattern `r"\s*[,:=\s]\s*"` matches only non-empty strings. Note also added prefix for avoiding a deprecation warning.
```python
>>> re.compile(r"\s*[,:=\s]\s*").split("a = b", 1)
['a', 'b']
```

It is recommended to run tests with enabled warnings for avoiding surprises.

**Comment by kif** [comment]
On Mon, 02 Jul 2018 22:15:05 -0700
Serhiy Storchaka <notifications@github.com> wrote:

> It is not working in Python 3.7 because the behavior of `re.split()` was changed. It supports now splitting on empty strings, and the pattern `r"\s*(?:[,:=]\s*)?"` can match an empty string.

Valentin will address the issue once silx has been released


> It is recommended to run tests with enabled warnings for avoiding surprises.

This has already been done in https://github.com/silx-kit/fabio/pull/244

Thanks for your help
-- 
Jérôme Kieffer

**Comment by vallsv** [comment]
I created #245 to fix the issue by fixing the regex. Thanks for the feed back.

**Pull request closed without merging**
