### PR TITLE
Add changelog and prepare a release

### PR DESCRIPTION
**Pull request by t20100**
This PR adds a `CHANGELOG.rst` file and bump the version to `0.10.0` in order to prepare a release of `fabio`.

### CODE REVIEW

**Comment by t20100** [comment]
I made the 0.10.0 changlog from the PR descriptions, it needs to be double checked.
For the other versions, I copied what's in the github release descriptions.

**Comment by kif** [comment]
I am surprised that the changelog is not seen as part of doc/sources/ ... that's where it is stored

**Comment by vallsv** [comment]
Yes, here it is https://github.com/silx-kit/fabio/blob/master/doc/source/Changelog.rst

**Comment by vallsv** [comment]
But i agree with thomas, it's better to move it to the root.
Then we should merge this documents.

**Pull request merged**
