### PR TITLE
Densification of sparse datasets

### PR DESCRIPTION
**Pull request by kif**
Densification -> LimaImage
related to  #443

### CODE REVIEW

**Comment by vallsv** [comment]
Anyway, i think you should use `fabio-densify` as entry point. THis entry points are shared with the while installed libs. `densify` sounds to me too generic and easy to overwrite by accident.

**Comment by kif** [comment]
I can check if it can be merged to the convert part ... reasonable idea.

**Comment by kif** [comment]
I changed the name of the CLI tool to `densify-Bragg` to mirror the `sparsify-Bragg` implemented in pyFAI.

**Comment by jonwright** [comment]
Obviously, I have no objection to any of this. I just didn't understand what it is meant for.

**Pull request merged**
