### PR TITLE
Rework APSGE contribution

### PR DESCRIPTION
**Pull request by jonwright**
This PR is a rework + clean up of the PR #395 from @joelvbernier

- Supports blanked GE file header
- Add blanked file tests
- Clean up the GEImage modules 
- Use `IndexError` and the requested frame is outside of the range
- Use `IOError` if there is problem to parse the file content

### CODE REVIEW

**Comment by vallsv** [comment]
If you want to update his branch you have to create a PR on his repository.

**Comment by vallsv** [comment]
This code is now ready for review. There is no more conda setup, nor non-standard EOL so it should be easier to it.

I have not only clean up the contribution but i have also cleaned up the code for readability and quality.

**Comment by joelvbernier** [comment]
Many thanks guys -- sorry that this is necessary, but there is a raft of GE data at this point that has the blanked header.  Requests to reinstate the old header have so far been unanswered.  High crimes, if you ak me 👎 

At any rate, my [software project](https://github.com/HEXRD/) (including Qt5/PySide2 GUI) uses fabio for raw data I/O and will build against the most recent package available going forward.

**Comment by joelvbernier** [comment]
@kif has a release been published with these changes?

**Comment by vallsv** [comment]
No, not yet.

**Comment by kif** [comment]
ESRF is busy restarting ...
We are all pretty busy for those who are not on holidays.

**Comment by joelvbernier** [comment]
Any desire to get a conda packaging scheme set up for fabio?  I could help with that.

**Comment by kif** [comment]
I can tag an upgrade the development version if you wish (i.e. not a full release, no release notes, no upgrad eof the doc)

**Comment by joelvbernier** [comment]
If we have a version tag to build against on PyPI that contains these "fixes", that would simplify our build for HEXRD :-)

**Pull request merged**
