### PR TITLE
testcase for FilenameObjects

### PR DESCRIPTION
**Pull request by jonwright**
I will try to push this to v0.10 branch as I assume I pushed to master and that was wrong. My apologies for being rather bad at git.

### CODE REVIEW

**Comment by jonwright** [comment]
So I was doing bad tearDown (my /tmp folder grows fabio folders, but I guess that is not this issue?).
Unrelated, a git checkout is 123 MB, so some test data are in .git but we are grabbing them over the network and adding/removing in /tmp for each test.

**Comment by jonwright** [comment]
Looking at the CI failure it seems it times out getting a test frame for 32 bit in an unrelated test. The intention is to try to protect the use cases we have over in fable, such as `fabio.open( FilenameObject )` but maybe I messed up somehow?

**Comment by vallsv** [comment]
That's good to me. Be careful i have patched your github branch.

**Comment by vallsv** [comment]
And i rebased it to the master.

**Pull request merged**
