### PR TITLE
Drop Python2 for real

### LINKED ISSUE #360: Remove Python2 compatibility code
While this code is left for version 0.10, it should be removed for 0.11, here are a few examples:

* [x] `from __future__ import `
* [x] `from six import`
* [x] Stop using unicode, prefer strings where needed 
* [x] drop argparse from third party as it is available from py2.7+
* [x] drop gzip from third party as it is available from py2.7+

### PR DESCRIPTION
**Pull request by kif**
Close #360

### CODE REVIEW

**Comment by vallsv** [comment]
Except my comment, it's fine.

Also `python3-six` could be removed from the debian packages?

**Comment by vallsv** [comment]
I have fixed the conflict

**Comment by vallsv** [comment]
Nice clean up BTW

**Comment by kif** [comment]
No new comments ... then I will merge

**Pull request merged**
