### PR TITLE
Added ability to read multiwire (.mpa) files

### PR DESCRIPTION
**Pull request by jbhopkins**
Added the ability to read in multiwire (.mpa) files. I tried to follow the contribution guide (https://fabio.readthedocs.io/en/latest/getting_started.html#adding-new-file-formats) but it appears to be a bit out of date. I also wasn't sure where to upload an image for testing.

Let me know what I should change so the new image reader can be integrated.

### CODE REVIEW

**Comment by vallsv** [comment]
You can send me the file by mail, and i will update our archive on http://www.silx.org/pub/fabio/testimages/

**Comment by vallsv** [comment]
BTW thanks for your contribution. I have no time right now to review your code, but i can do it next week. And i would prefer to wait for a comment of @kif before merging it anyway.

But would it be possible to have an URL to this file format? Thanks a lot.

**Comment by jbhopkins** [comment]
Happy to help. I've put your library to good use in my own software, and wanted to give back. No problem with waiting for code review.

I don't have a URL for the file format. It's for old multiwire detectors (technically 2D multiwire detector proportional chamber (MWPC)). These are mostly used in older rigaku homesource instruments.

The python implementation of the file format was first done by me in RAW (https://sourceforge.net/projects/bioxtasraw/), at the request of a user one of these instruments. The code was based on the code the users were currently using in SAXSGui (http://saxsgui.com/), which was provided to as matlab code by Karsten (the author of that software). 

The python version of the reader, which I've lightly modified to fit your structure, has been used successfully at their homesource facility.

I've sent you a sample data file via e-mail.

**Comment by vallsv** [comment]
Hi. Thanks a lot.
I add a commit to your pull request. It clean up the tests, and fix the file download.

I guess if you use this git comand, your branch will be updated:
```
git pull
git log -1 # to be sure the last commit is my commit
```

Then you can check it by using:
```
./run_tests.py -v -i fabio.test.testmpaimage
```

**Comment by vallsv** [comment]
If you would like to check, there is an issue on Python 3. 
```
ERROR: test_read (fabio.test.testmpaimage.TestMpa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/fabio/test/testmpaimage.py", line 57, in test_read
    obj.read(path)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/fabio/mpaimage.py", line 100, in read
    self._readheader(infile)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/fabio/mpaimage.py", line 69, in _readheader
    if line.find('=') > -1:
TypeError: Type str doesn't support the buffer API
```

**Comment by jbhopkins** [comment]
That would make sense. I typically only work on python 2. It might take me a bit to getting a python 3 environment set up and working to test it on. You're welcome to fix it yourself if you want, or I will get to it when I can.

**Comment by vallsv** [comment]
Ok. Here we have. My env was configured, then it was easy.

**Comment by jbhopkins** [comment]
Turns out building a python3 environment was pretty easy. I just tested your commits, and on my machine they test fine with 3.6 and 2.7. Let me know if there's anything else you want me to do, and thanks for cleaning that up for me!

**Comment by kif** [comment]
I submitted you a PR to your branch with a few correction. Could you check them and merge ?

**Comment by jbhopkins** [comment]
The changes look fine (I only reviewed those to the MPA file, not all the documentation changes). I tested them, and it tests fine (in 2.7). I've merged in the pull request.

**Comment by vallsv** [comment]
Well. That's a nightmare in the commits now. 34 files changed.
I will close this PR and manage it into another. I don't think i can manage it else.

**Comment by vallsv** [comment]
Then i created https://github.com/silx-kit/fabio/pull/143.
There is no other choices without spend a lot of effort i think.

**Comment by vallsv** [comment]
Thanks a lot for the contribution. I guess it will be merge in few hours, after tests.

**Pull request closed without merging**
